{{- if and .Values.secrets.create (not .Values.secrets.existingSecret) }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "data-process.fullname" . }}-secrets
  namespace: {{ .Values.namespace }}
  labels:
    app: {{ include "data-process.fullname" . }}
type: Opaque
stringData:
  DATABASE_URL: {{ .Values.secrets.data.DATABASE_URL | quote }}
  R2_ACCOUNT_ID: {{ .Values.secrets.data.R2_ACCOUNT_ID | quote }}
  R2_ACCESS_KEY_ID: {{ .Values.secrets.data.R2_ACCESS_KEY_ID | quote }}
  R2_SECRET_ACCESS_KEY: {{ .Values.secrets.data.R2_SECRET_ACCESS_KEY | quote }}
  R2_BUCKET_NAME: {{ .Values.secrets.data.R2_BUCKET_NAME | quote }}
{{- end }}
