{{- if and .Values.trackService.enabled (not .Values.trackService.clickHouse.existingSecret) .Values.trackService.clickHouse.connectionString -}}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "trackService.clickhouseSecretName" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "featbit-rda.labels" . | nindent 4 }}
    app.kubernetes.io/component: track-service
type: Opaque
stringData:
  {{ .Values.trackService.clickHouse.existingSecretKey }}: {{ .Values.trackService.clickHouse.connectionString | quote }}
{{- end }}
