{{- if and .Values.trackService.enabled (not .Values.trackService.envSecret.existingSecret) .Values.trackService.envSecret.signingKey -}}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "trackService.signingKeySecretName" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "featbit-rda.labels" . | nindent 4 }}
    app.kubernetes.io/component: track-service
type: Opaque
stringData:
  {{ .Values.trackService.envSecret.existingSecretKey }}: {{ .Values.trackService.envSecret.signingKey | quote }}
{{- end }}
