{{- if and .Values.web.enabled (not .Values.web.database.existingSecret) .Values.web.database.connectionString -}}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "web.databaseSecretName" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "featbit-rda.labels" . | nindent 4 }}
    app.kubernetes.io/component: web
type: Opaque
stringData:
  {{ .Values.web.database.existingSecretKey }}: {{ .Values.web.database.connectionString | quote }}
{{- end }}
